var www = ["demoscene",
"demoscene",
"demoscene",
"ã and eridem",
"ã and eridem",
"ã and eridem",
"ã and eridem",
"_KpRñA_",
"_KpRñA_",
"_KpRñA_",
"_KpRñA_",
"REPEAT",
"REPEAT",
"REPEAT",
"REPEAT",
"wake up",
"food",
"work",
"computer",
"coding",
"home",
"games",
"sleep",
"work",
"eat",
"sleep",
"code",
"sleep",
"code",
"repeat",
"again",
"and again",
"night",
"party",
"hard",
"drink",
"harder",
"beer",
"fireball",
"shot",
"rum",
"anything",
"everything",
"fall down",
"stand up",
"sex",
"hangover",
"hamburger",
"sleep",
"repeat",
"breathe",
"code",
"walk",
"back",
"repeat",
"work",
"exploding",
"kittens",
"friends",
"day",
"night",
"day again",
"sleep",
"repeat",
"edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16",
    "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16",
    "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16",
"edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16", "edison 16"];

var wwwIndex = -1;